-- DuckDB schema for t_bet, aligned to schema/schema.txt (ClickHouse GDP_GMWDS_Raw.t_bet).
-- Use DECIMAL(19,4) for all monetary columns to avoid "value is out of range" when
-- values exceed DECIMAL(9,4) or DECIMAL(10,4) (e.g. wager 100000, casino_win -1900000).
-- DuckDB: DECIMAL(19,4) range is ± 10^15 with 4 decimal places.
--
-- When registering from pandas: use trainer.duckdb_schema.prepare_bets_for_duckdb(bets_df)
-- before con.register("bets", df) so monetary columns are float64 → DuckDB DOUBLE,
-- avoiding narrow DECIMAL inference in window expressions.

CREATE TABLE IF NOT EXISTS bets (
    bet_id                 BIGINT,
    is_back_bet            INTEGER,
    base_ha                DECIMAL(19,4),
    bet_type               VARCHAR,
    bet_uuid               VARCHAR,
    bonus                  DECIMAL(19,4),
    casino_loss_from_nn     DECIMAL(19,4),
    casino_win              DECIMAL(19,4),
    commission              DECIMAL(19,4),
    game_id                 BIGINT,
    is_lump_sum_payout      INTEGER,
    max_wager               DECIMAL(19,4),
    payout_complete_dtm     TIMESTAMP,
    gaming_day              DATE,
    payout_ha               DECIMAL(19,4),
    payout_odds              DECIMAL(19,4),
    player_id               BIGINT,
    position_code           VARCHAR,
    position_idx            INTEGER,
    position_label          VARCHAR,
    session_id              BIGINT,
    is_settled              INTEGER,
    status                  VARCHAR,
    std_dev                 DECIMAL(19,4),
    table_id                INTEGER,
    theo_win                DECIMAL(19,4),
    theo_win_cash           DECIMAL(19,4),
    true_odds               DECIMAL(19,4),
    wager                   DECIMAL(19,4),
    wager_nn                DECIMAL(19,4),
    chips_paid              VARCHAR,
    chips_wagered           VARCHAR,
    chipsvalue_by_chipset   VARCHAR,
    chipset_label           VARCHAR,
    tip_amount              DECIMAL(19,4),
    chips_tip               VARCHAR,
    bet_cards               VARCHAR,
    increment_wager         DECIMAL(19,4),
    bet_cards_sum           DECIMAL(19,4),
    adjusted_theo_win       DECIMAL(19,4),
    short_bet_name_en       VARCHAR,
    short_bet_name_zh       VARCHAR,
    mixed_stack             INTEGER,
    auto_resolve_stack      INTEGER,
    type_of_bet             VARCHAR,
    bet_payout_type         VARCHAR,
    payout_value            DECIMAL(19,4),
    bonus_game_offered      INTEGER,
    is_jackpot              INTEGER,
    bet_reconciled_at       TIMESTAMP,
    __ts_ms                 BIGINT,
    __op                    VARCHAR,
    __deleted               VARCHAR,
    __etl_insert_Dtm        TIMESTAMP,
    -- Trainer pipeline may add:
    canonical_id            VARCHAR,
    loss_streak             INTEGER,
    run_id                  INTEGER,
    minutes_since_run_start DOUBLE,
    _range_sort_key         TIMESTAMP
);
