from __future__ import annotations

"""Internal validator config shard."""

VALIDATOR_ALERT_RETENTION_DAYS = 30
VALIDATOR_FINALIZE_ON_HORIZON = True
VALIDATOR_FINALIZE_MINUTES = 45
VALIDATOR_FRESHNESS_BUFFER_MINUTES: int = 2
VALIDATOR_EXTENDED_WAIT_MINUTES: int = 15
VALIDATOR_FINALITY_HOURS: int = 1
VALIDATOR_FETCH_PRE_CONTEXT_MINUTES: int = 60
VALIDATOR_FETCH_MAX_LOOKBACK_MINUTES: int = 180
VALIDATOR_FETCH_MAX_LOOKBACK_MINUTES_CAP: int = 24 * 60
VALIDATOR_NO_BET_RETRY_MAX_ALERTS: int = 50
VALIDATOR_NO_BET_RETRY_MAX_WINDOW_MINUTES: int = 240
VALIDATOR_NO_BET_BET_ID_LOOKUP_ENABLED: bool = True
VALIDATOR_NO_BET_BET_ID_CHUNK_SIZE: int = 500

